/**
 * Auto-generate TODO file from unhandled components
 *
 * Creates a TypeScript file containing unhandled components that must be configured
 * before migration can proceed. This file is used by the auto-merge process.
 *
 * @module auto-generate-todo
 */

import fs from 'fs/promises'
import path from 'path'
import type { UnhandledComponent } from './mdx-to-payload-blocks.js'

/**
 * Generate TODO file from unhandled components
 *
 * Creates `migration/COMPONENT-REGISTRATION-TODO.ts` containing all unhandled
 * components discovered during migration. Each component is initialized with
 * default values and marked as `isBlocking: true`.
 *
 * @param components - Array of unhandled components with usage counts
 * @returns Path to the generated TODO file
 *
 * @example
 * ```typescript
 * const unhandledComponents = [
 *   { name: 'Section', usageCount: 6601, componentType: 'block', firstSeenFile: '...', firstSeenLine: 10 },
 *   { name: 'Image', usageCount: 5292, componentType: 'inline', firstSeenFile: '...', firstSeenLine: 15 }
 * ]
 * await generateTodoFile(unhandledComponents)
 * // Creates: migration/COMPONENT-REGISTRATION-TODO.ts
 * ```
 */
export async function generateTodoFile(components: UnhandledComponent[]): Promise<string> {
  const timestamp = new Date().toISOString()
  const todoFilePath = path.join(process.cwd(), 'migration', 'COMPONENT-REGISTRATION-TODO.ts')

  // Sort by usage count (highest first) for prioritization
  const sortedComponents = components.sort((a, b) => b.usageCount - a.usageCount)

  // Generate file header
  let content = `/**
 * Unregistered Components - Auto-generated
 *
 * Generated: ${timestamp}
 * Components: ${components.length}
 *
 * These components were detected during migration and must be configured.
 *
 * IMPORTANT: This file is automatically generated and merged into the main
 * component registry. Configure each component by:
 * 1. Setting the correct componentType ('block', 'inline', 'both')
 * 2. Setting canRenderBlock and canRenderInline flags
 * 3. Implementing the Payload block type if needed
 * 4. Updating status to 'implemented' when complete
 *
 * After configuration, re-run the migration script.
 */

import type { ComponentMapping } from '../../../src/lib/component-registry.js'

export const UNREGISTERED_COMPONENTS: Record<string, ComponentMapping> = {
`

  // Generate component entries
  for (const component of sortedComponents) {
    const { name, usageCount, componentType, firstSeenFile, firstSeenLine } = component

    // Infer canRenderBlock and canRenderInline from componentType
    const canRenderBlock = componentType === 'block' || componentType === 'both'
    const canRenderInline = componentType === 'inline' || componentType === 'both'

    content += `  '${name}': {
    status: 'needs-work' as const,
    componentType: '${componentType}' as const,
    canRenderBlock: ${canRenderBlock},
    canRenderInline: ${canRenderInline},
    payloadBlockType: undefined,
    mdxUsageCount: ${usageCount},
    fields: {},
    todos: [
      'Configure component type',
      'Set rendering capabilities',
      'Implement Payload block or inline block',
      'Test with sample MDX',
    ],
    isBlocking: true,  // Blocks migration until configured
    // First seen: ${firstSeenFile}${firstSeenLine ? `:${firstSeenLine}` : ''}
  },

`
  }

  content += `}
`

  // Write file
  await fs.writeFile(todoFilePath, content, 'utf-8')

  return todoFilePath
}

/**
 * Check if TODO file exists
 *
 * @returns True if TODO file exists, false otherwise
 */
export async function todoFileExists(): Promise<boolean> {
  const todoFilePath = path.join(process.cwd(), 'migration', 'COMPONENT-REGISTRATION-TODO.ts')
  try {
    await fs.access(todoFilePath)
    return true
  } catch {
    return false
  }
}

/**
 * Delete TODO file
 *
 * Removes the auto-generated TODO file. Typically called after successful
 * merge or when user wants to regenerate from scratch.
 *
 * @returns True if file was deleted, false if it didn't exist
 */
export async function deleteTodoFile(): Promise<boolean> {
  const todoFilePath = path.join(process.cwd(), 'migration', 'COMPONENT-REGISTRATION-TODO.ts')
  try {
    await fs.unlink(todoFilePath)
    return true
  } catch {
    return false
  }
}
